### ISSUE TITLE
QR bill invalid if amount has leading zero (like 0.30)

### ISSUE THREAD

**Issue by entreprenr** [manuelbl/SwissQRBill#19]
I tested the QR bill with Raiffeisen bank with an amount of 0.30 (30 Rappen).

Raiffeisen bank said the QR bill was invalid, because the amount contained "0.30" instead of ".30" as it's supposed to be according to them. So they actually rejected the QR bill.

And here is the text from paymentstandards.ch:
"The amount element is to be entered without leading zeroes, including decimal separators and two decimal places."
(ig-qr-bill-en.pdf Page 27)

Since we set a BigDecimal number for the amount, I think the SwissQRBill library should handle this.

**Comment by entreprenr** [comment]
Sorry, duplicate issue.

**Comment by manuelbl** [comment]
No problem.

I wonder how many people will be affected by this issue. The Raiffeisen app is probably correct (tough very picky). But the majority of implementations either hasn't read the specification in detail or interprets it differently. "0.30" (instead of ".30") is more likely to be accepted by scanners and therefore implemented in this library.
