### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by xshaker77** [manuelbl/SwissQRBill#23]
Would it possible to offer an option for a custom logo instead of a Swiss cross?

**Comment by manuelbl** [comment]
What would be the added value of offering an option producing QR bills in violation of the standard?

If you absolutely want to have such QR bills, why not put your custom logo on top of the QR bill? The QR code and Swiss cross always have the same size and position. So that shouldn't be too difficult.

**Comment by xshaker77** [comment]
Yes, I know the spec: https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf (chapter 5.4.2, page 35.) is precise in that matter, although got that question because of demo purposes.

> What would be the added value of offering an option producing QR bills in violation of the standard?
> [...]

**Comment by manuelbl** [comment]
The effort to implement this feature such that it works with all the currently supported output formats (SVG, PNG, PDF) is very high and would heavily affect all library users that have implemented their own `Canvas` class. Compared to the minimal added value (if at all), the effort is not justified. So I have no plans to implement it.
