### ISSUE TITLE
Issue with AppendToPDF

### ISSUE THREAD

**Issue by MathiasZaja** [manuelbl/SwissQRBill#32]
Hi Manuel,
I'm trying your great SwissQRBill project.
QRBillExample works fine. However  trying AppendToPDF I get:
**Exception in thread "main" java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.load(Ljava/io/InputStream;)Lorg/apache/pdfbox/pdmodel/PDDocument;
at net.codecrete.qrbill.canvas.PDFCanvas.<init>(PDFCanvas.java:83)**
I develop in Eclipse environment and have your 2 jars: qrbill-generator-2.5.2.jar & qrcodegen-1.6.0.jar as well as apahe's fontbox-3.0.0-RC1.jar & pdfbox-3.0.0-RC1.jar on Java Build Path.
Am I missing something ?
Kind regards
PS:
If I'd like just to generate the QR-Code and have it displayed on the Web page, how should I do it ?

**Comment by manuelbl** [comment]
SwissQRBill is not compatible with version 3 of *pdfbox*. To fix it, downgrade to version 2.0.23 of *pdfbox* and *fontbox*. If you are managing dependencies with Maven or Gradle, this should work without automatically.

In order to display the QR code on a web page, you need to implement a web request returning an SVG file. You can more or less go with the code from the GitHub home page. The main difference is the call to `setOutputSize()` to restrict it to the QR code only:

        // Setup bill
        Bill bill = new Bill();
        bill.setAccount("CH4431999123000889012");
        bill.setAmountFromDouble(199.95);
        bill.setCurrency("CHF");

        // Set creditor
        Address creditor = new Address();
        creditor.setName("Robert Schneider AG");
        creditor.setAddressLine1("Rue du Lac 1268/2/22");
        creditor.setAddressLine2("2501 Biel");
        creditor.setCountryCode("CH");
        bill.setCreditor(creditor);

        // more bill data
        bill.setReference("210000000003139471430009017");
        bill.setUnstructuredMessage("Abonnement für 2020");

        // Set debtor
        Address debtor = new Address();
        debtor.setName("Pia-Maria Rutschmann-Schnyder");
        debtor.setAddressLine1("Grosse Marktgasse 28");
        debtor.setAddressLine2("9400 Rorschach");
        debtor.setCountryCode("CH");
        bill.setDebtor(debtor);

        // Generate QR code only
        bill.getFormat().setOutputSize(OutputSize.QR_CODE_ONLY);

        // Generate QR bill
        byte[] svg = QRBill.generate(bill);

The resulting byte array (*svg*) should then be sent as the response using the content type `image/svg+xml`. How this is done depends on the Java web framework you're using.

**Comment by MathiasZaja** [comment]
Hi Manuel,
Thanks for your reply.
I downgraded to version 2.0.23 of pdfbox and fontbox and it fixed the issue.
QR_CODE_ONLY does exactly what I need (I've discovered that option later on, sorry)

Please consider the issue as closed.

I could not implement a dedicated web request to return SVG file since I have already one request for the whole page and QR-Code is just a part of the page. However I could simply generate the QR-Code file, put it on disk and embed it in the page. Maybe it is not very elegant, but it does what I need.

I'd like to to compliment you for the great job you've done as well as the quality of your code as for the Bill data validation documentation.
Kind regards.
