### ISSUE TITLE
Add graphic to PDFCanvas()

### ISSUE THREAD

**Issue by LinuxSquare** [manuelbl/SwissQRBill#47]
Hi there

Is there a way to add a graphic (svg or png format) to a PDF e.g. for a company logo?
I haven't read anything in the JavaDocs or similar.

Thank you in advance.

**Comment by manuelbl** [comment]
This library does not support adding graphics. It focuses on the QR bill part only.

For PDF documents, this library builds on [Apache PDFBox](https://pdfbox.apache.org/). It supports all kind of drawing operations, most likely also PNG and possibly SVG. Thus, I recommend to investigate this option.

In order to use it together with this library, you can either create the PDF with a single QR bill page with this library and then add the graphics using PDFBox. Or you can create a PDF document with PDFBox and then add the QR bill on an existing or additional page with this library. The latter is shown in this [example](https://github.com/manuelbl/SwissQRBill/blob/master/examples/append_to_pdf/src/main/java/net/codecrete/qrbill/examples/AppendToPDF.java).

I'm also considering extending this library such that the QR bill can be added while the PDF document is already open for writing. The two approaches describe above open, write and close the PDF document twice.

**Comment by LinuxSquare** [comment]
Hi there @manuelbl 

Thank you very much. Your suggestion has solved my problem.
